function goList(){
 
    document.location.href="index2.html";
}
function goTarotList(){
 
    document.location.href="index3.html";
}
function goConstellationList(){
 
    document.location.href="index4.html";
}
function goZodiacList(){
 
    document.location.href="index5.html";
}
function showTarot(){
    var str='<div class="col-md-2 mb-3">                                <select class="custom-select" id="validationDefault04" required>                                    <option selected>城市</option>                                    <option value="1">台北市</option>                                    <option value="2">台中市</option>                                    <option value="3">高雄市</option>                                </select>                            </div>                            <div class="col-md-2 mb-3">                                <select class="custom-select" id="validationDefault04" required>                                    <option selected>詢問項目</option>                                    <option value="1">工作</option>                                    <option value="2">感情</option>                                    <option value="3">健康</option>                                </select>                            </div>                            <div class="col-md-2 mb-3">                                <select class="custom-select" id="validationDefault04" required>                                    <option selected>服務模式</option>                                    <option value="1">線上算</option>                                    <option value="2">留言</option>                                    <option value="3">網頁算命</option>                                </select>                            </div>                            <div class="col-md-2 mb-3">                                <select class="custom-select" id="validationDefault04" required>                                    <option selected>價格</option>                                    <option value="1">0~300</option>                                    <option value="2">301~600</option>                                    <option value="2">601~1000</option>                                    <option value="3">1001以上</option>                                </select>                            </div>                            <div class="col-md-2 mb-3">                                <input type="text" class="form-control" id="validationDefault05" placeholder="關鍵字">                            </div>                            <div class="col-md-2 mb-3">                               <button class="btn btn-primary center"  onclick="goTarotList()">尋找服務</button>                            </div>'
    document.getElementById("form-row").innerHTML = str;
}
function showConstellation(){
    var str='<div class="col-md-2 mb-3">                                <select class="custom-select" id="validationDefault04" required>                                    <option selected>城市</option>                                    <option value="1">台北市</option>                                    <option value="2">台中市</option>                                    <option value="3">高雄市</option>                                </select>                            </div>                            <div class="col-md-2 mb-3">                                <select class="custom-select" id="validationDefault04" required>                                    <option selected>詢問項目</option>                                    <option value="1">工作</option>                                    <option value="2">感情</option>                                    <option value="3">健康</option>                                </select>                            </div>                            <div class="col-md-2 mb-3">                                <select class="custom-select" id="validationDefault04" required>                                    <option selected>服務模式</option>                                    <option value="1">線上算</option>                                    <option value="2">留言</option>                                    <option value="3">網頁算命</option>                                </select>                            </div>                            <div class="col-md-2 mb-3">                                <select class="custom-select" id="validationDefault04" required>                                    <option selected>價格</option>                                    <option value="1">0~300</option>                                    <option value="2">301~600</option>                                    <option value="2">601~1000</option>                                    <option value="3">1001以上</option>                                </select>                            </div>                            <div class="col-md-2 mb-3">                                <input type="text" class="form-control" id="validationDefault05" placeholder="關鍵字">                            </div>                            <div class="col-md-2 mb-3">                               <button class="btn btn-primary center"  onclick="goConstellationList()">尋找服務</button>                            </div>'
    document.getElementById("form-row").innerHTML = str;
}
function showZodiac(){
    var str='<div class="col-md-2 mb-3">                                <select class="custom-select" id="validationDefault04" required>                                    <option selected>城市</option>                                    <option value="1">台北市</option>                                    <option value="2">台中市</option>                                    <option value="3">高雄市</option>                                </select>                            </div>                            <div class="col-md-2 mb-3">                                <select class="custom-select" id="validationDefault04" required>                                    <option selected>詢問項目</option>                                    <option value="1">工作</option>                                    <option value="2">感情</option>                                    <option value="3">健康</option>                                </select>                            </div>                            <div class="col-md-2 mb-3">                                <select class="custom-select" id="validationDefault04" required>                                    <option selected>服務模式</option>                                    <option value="1">線上算</option>                                    <option value="2">留言</option>                                    <option value="3">網頁算命</option>                                </select>                            </div>                            <div class="col-md-2 mb-3">                                <select class="custom-select" id="validationDefault04" required>                                    <option selected>價格</option>                                    <option value="1">0~300</option>                                    <option value="2">301~600</option>                                    <option value="2">601~1000</option>                                    <option value="3">1001以上</option>                                </select>                            </div>                            <div class="col-md-2 mb-3">                                <input type="text" class="form-control" id="validationDefault05" placeholder="關鍵字">                            </div>                            <div class="col-md-2 mb-3">                               <button class="btn btn-primary center"  onclick="goZodiacList()">尋找服務</button>                            </div>'
    document.getElementById("form-row").innerHTML = str;
}
function buybuybuy(){
    document.location.href="buySuccess.html";
    console.log('aaa');
}